/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
uint8_t numero_1=0;
uint8_t numero_2=0;
char operador='+';

void suma(numero_1, numero_2);
uint8_t resta(numero_1, numero_2);

int main(void)
{
    /* Loop forever */
	for(;;);
}
