/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f411xe.h"
#include <stdint.h>
#include <stm32f4xx.h>

void init_gpio(void);
void init_tim3(void);

int main(void)
{
    // Hardware initialization code here
    init_gpio();
    init_tim3();

    while (1)
    {
        // Main loop code here
    }
    return 0;
}

void init_gpio(void)
{
    // Enable GPIOA clock
    RCC->AHB1ENR |= (1 << 0);
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN_Msk;

    // Configure PA5 as output
    GPIOA->MODER &= ~(0b11 << GPIO_MODER_MODE5_Pos); // Clear mode bits for PA5
    GPIOA->MODER |= (0b01 << GPIO_MODER_MODE5_Pos); // Set PA5 as general purpose output mode

    GPIOA->OTYPER &= ~(GPIO_OTYPER_OT5); // Set PA5 as push-pull

    GPIOA->OSPEEDR &= ~(0b11 << GPIO_OSPEEDR_OSPEED5_Pos); // Clear speed bits for PA5
    GPIOA->OSPEEDR |= (0b01 << GPIO_OSPEEDR_OSPEED5_Pos); // Set PA5 speed to high

    GPIOA->PUPDR &= ~(0b11 << GPIO_PUPDR_PUPD5_Pos); // No pull-up, pull-down for PA5

    GPIOA->ODR |= (GPIO_ODR_OD5); // Set PA5 high (turn on LED)
}

// Set tim3 for led beeps and calls for interrupts
void init_tim3(void){
    RCC->APB1ENR |= RCC_APB1ENR_TIM3EN_Msk; //

    TIM3->CNT = 0;
    TIM3->PSC = (1000-1); //Increasing every 0.1 us
    TIM3->ARR = (2500-1); //It generates an interrupt every 250 us

    TIM3->CR1 &= ~(0b11 << TIM_CR1_CEN_Pos); //DIsable TIM3
    TIM3->CR1 |=(TIM_CR1_ARPE); //APR preload
    TIM3->CR1 &= ~(TIM_CR1_DIR_Pos); //Clean

    TIM3->DIER |= (TIM_DIER_UIE); //Enable interrupt for update

    NVIC_EnableIRQ(TIM3_IRQn); //Interrupt registration

    TIM3->CR1 |= TIM_CR1_CEN; //Enable
    }

//Interrupt service routine
void TIM3_IRQHandler(void){
    //Check if the update interrupt flag is set
    if (TIM3->SR && TIM_SR_UIF) {
        TIM3->SR &= ~TIM_SR_UIF; // Clear the update interrupt flag

        GPIOA->ODR ^= GPIO_ODR_OD5; // Toggle PA5 (LED)
    }
}