#!/usr/bin/env bash
#
# setup-stm32.sh — make a fresh STM32 CMake project build and debug in VS Code.
#
# Works with both kinds of project, detected automatically:
#
#   CubeMX   generated by STM32CubeMX with Toolchain/IDE = CMake (has a .ioc)
#   Empty    created by the STM32Cube extension's "Empty project" wizard
#            (has project-description.json, no .ioc, no HAL)
#
# Neither generator leaves a project that works out of the box. This script
# creates or fixes:
#
#   layout       Empty only: sources in Src/ and Inc/ are moved to Core/Src and
#                Core/Inc, and the paths in cmake/files.cmake, cmake/flags.cmake
#                and project-description.json are updated to match
#   .settings/   bundle store: pins the ST toolchain, cmake, ninja, gdbserver...
#                (without bundles-lock.store.json, cube-cmake cannot find
#                arm-none-eabi-gcc and the configure step fails; the Empty
#                wizard writes it as "{}")
#   .vscode/     settings.json, launch.json (with the ST-LINK Stop fix),
#                tasks.json, c_cpp_properties.json
#   .clangd, .gitignore
#
# Then it configures and builds the Debug preset to prove the project works.
#
# Usage:  setup-stm32.sh [--force] [--dry-run] [--no-build] <project_dir>
#
#   --force     overwrite existing config files (originals are kept as *.bak)
#   --dry-run   only print what would be done
#   --no-build  skip the configure + build check
#
# Only the Core/Src, Core/Inc layout is supported.

set -euo pipefail

FORCE=0
DRY_RUN=0
DO_BUILD=1
PROJ=""

usage() { sed -n '/^# Usage:/,/^# Only/p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --force)    FORCE=1 ;;
        --dry-run)  DRY_RUN=1 ;;
        --no-build) DO_BUILD=0 ;;
        -h|--help)  usage 0 ;;
        -*)         echo "Unknown option: $1" >&2; usage 1 ;;
        *)          PROJ="$1" ;;
    esac
    shift
done
[[ -n "$PROJ" ]] || usage 1

info()  { printf '  \033[32m✔\033[0m %s\n' "$*"; }
skip()  { printf '  \033[33m•\033[0m %s\n' "$*"; }
fail()  { printf '\n\033[31m✘ %s\033[0m\n' "$*" >&2; exit 1; }
title() { printf '\n\033[1m%s\033[0m\n' "$*"; }

# run <description> <command...>: execute, or only describe it in --dry-run
run() {
    local what="$1"; shift
    if [[ $DRY_RUN -eq 1 ]]; then info "$what (would do)"; else "$@"; info "$what"; fi
}

# ---------------------------------------------------------------------------
title "1. Checking the project"
# ---------------------------------------------------------------------------
[[ -d "$PROJ" ]] || fail "Not a directory: $PROJ"
PROJ="$(cd "$PROJ" && pwd)"

shopt -s nullglob
iocs=("$PROJ"/*.ioc)
shopt -u nullglob

if [[ ${#iocs[@]} -gt 1 ]]; then
    fail "Found ${#iocs[@]} .ioc files in $PROJ, expected one."
elif [[ ${#iocs[@]} -eq 1 ]]; then
    KIND="CubeMX"
elif [[ -f "$PROJ/project-description.json" ]]; then
    KIND="Empty"
else
    fail "Not an STM32 project: no .ioc file (CubeMX) and no project-description.json (VS Code Empty project)."
fi

if [[ "$KIND" == "CubeMX" ]]; then
    IOC="${iocs[0]}"
    ioc_get() { grep -m1 "^$1=" "$IOC" | cut -d= -f2- | tr -d '\r' || true; }

    PROJECT_NAME="$(ioc_get ProjectManager.ProjectName)"
    TOOLCHAIN="$(ioc_get ProjectManager.TargetToolchain)"
    MAIN_LOCATION="$(ioc_get ProjectManager.MainLocation)"
    BOARD="$(ioc_get board)"
    DEVICE="$(ioc_get Mcu.CPN)"
    FAMILY="$(ioc_get Mcu.Family)"

    [[ "$TOOLCHAIN" == "CMake" ]] \
        || fail "Toolchain in the .ioc is '$TOOLCHAIN'. In CubeMX: Project Manager > Project > Toolchain/IDE = CMake, then regenerate."

    if [[ "$MAIN_LOCATION" != "Core/Src" || ! -d "$PROJ/Core/Src" ]]; then
        fail "Sources are in '$MAIN_LOCATION', not in Core/Src.
  CubeMX puts Src/ and Inc/ at the root when Application Structure is 'Basic'.
  Fix: in CubeMX, Project Manager > Project > Application Structure = Advanced,
  then generate again, preferably into a new folder so the old Src/ and Inc/
  do not stay behind."
    fi

    for f in CMakeLists.txt CMakePresets.json cmake/stm32cubemx/CMakeLists.txt; do
        [[ -f "$PROJ/$f" ]] || fail "Missing $f — was the code generated from CubeMX?"
    done

    # Cortex core from the family, for .settings/ide.store.json
    case "$FAMILY" in
        STM32F0|STM32C0)                        CORE="Cortex-M0" ;;
        STM32G0|STM32L0|STM32U0|STM32WL0)       CORE="Cortex-M0+" ;;
        STM32F1|STM32F2|STM32L1)                CORE="Cortex-M3" ;;
        STM32F3|STM32F4|STM32G4|STM32L4|STM32WB|STM32WL) CORE="Cortex-M4" ;;
        STM32F7|STM32H7)                        CORE="Cortex-M7" ;;
        STM32L5|STM32U5|STM32H5|STM32WBA|STM32U3) CORE="Cortex-M33" ;;
        *) fail "Unknown MCU family '$FAMILY' — add it to the CORE table in this script." ;;
    esac
else
    DESC="$PROJ/project-description.json"
    for f in CMakeLists.txt CMakePresets.json cmake/target.cmake cmake/files.cmake cmake/flags.cmake; do
        [[ -f "$PROJ/$f" ]] || fail "Missing $f — was this project created with the STM32Cube extension's 'Empty project' wizard?"
    done

    # Reads a "key": "value" string from project-description.json (first match)
    desc_get() { grep -m1 -o "\"$1\": *\"[^\"]*\"" "$DESC" | sed 's/.*: *"\(.*\)"/\1/' || true; }

    PROJECT_NAME="$(desc_get name)"
    BOARD="$(desc_get board)"
    DEVICE="$(desc_get mcu)"
    CORE="$(sed -n 's/^set(CMSIS_Dcore \(.*\))/\1/p' "$PROJ/cmake/target.cmake")"
fi

[[ -n "$PROJECT_NAME" && -n "$DEVICE" && -n "$CORE" ]] \
    || fail "Could not read the project name, device and core of this $KIND project."

info "Type    : $KIND project"
info "Project : $PROJECT_NAME"
info "Board   : ${BOARD:-<none>}   Device: $DEVICE ($CORE)"

# ---------------------------------------------------------------------------
title "2. Source layout (Core/Src, Core/Inc)"
# ---------------------------------------------------------------------------
if [[ "$KIND" == "CubeMX" ]]; then
    skip "Generated by CubeMX in Core/ (checked above)"
else
    if [[ -d "$PROJ/Src" && -d "$PROJ/Core/Src" ]]; then
        fail "Both Src/ and Core/Src/ exist. Merge them by hand into Core/Src, delete Src/, then run this again."
    elif [[ -d "$PROJ/Src" ]]; then
        run "Moved Src/ to Core/Src/" bash -c 'mkdir -p "$1/Core" && mv "$1/Src" "$1/Core/Src"' _ "$PROJ"
    elif [[ -d "$PROJ/Core/Src" ]]; then
        skip "Core/Src/ already in place"
    else
        fail "No Src/ or Core/Src/ folder with the sources."
    fi

    if [[ -d "$PROJ/Inc" && -d "$PROJ/Core/Inc" ]]; then
        if [[ -z "$(ls -A "$PROJ/Inc")" ]]; then
            run "Removed empty Inc/" rmdir "$PROJ/Inc"
        else
            fail "Both Inc/ and Core/Inc/ exist. Merge them by hand into Core/Inc, delete Inc/, then run this again."
        fi
    elif [[ -d "$PROJ/Inc" ]]; then
        run "Moved Inc/ to Core/Inc/" bash -c 'mkdir -p "$1/Core" && mv "$1/Inc" "$1/Core/Inc"' _ "$PROJ"
    elif [[ -d "$PROJ/Core/Inc" ]]; then
        skip "Core/Inc/ already in place"
    else
        run "Created Core/Inc/" mkdir -p "$PROJ/Core/Inc"
    fi

    # fix_paths <relative path> <sed script>: rewrite the old Src/Inc paths.
    # The sed patterns only match the old form, so running twice changes nothing.
    fix_paths() {
        local rel="$1" dst="$PROJ/$1" new
        new="$(sed "$2" "$dst")"
        if [[ "$new" == "$(cat "$dst")" ]]; then
            skip "$rel (paths already point to Core/)"; return
        fi
        if [[ $DRY_RUN -eq 1 ]]; then
            info "$rel (would update paths to Core/)"; return
        fi
        cp "$dst" "$dst.bak"
        printf '%s\n' "$new" > "$dst"
        info "$rel (paths updated to Core/, original kept as $rel.bak)"
    }

    # cmake/*.cmake is what the build uses; project-description.json is what the
    # extension regenerates those files from, so both must agree.
    fix_paths cmake/files.cmake        's#${CMAKE_CURRENT_SOURCE_DIR}/Src/#${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/#g'
    fix_paths cmake/flags.cmake        's#${CMAKE_CURRENT_SOURCE_DIR}/Inc"#${CMAKE_CURRENT_SOURCE_DIR}/Core/Inc"#g'
    fix_paths project-description.json 's#"path": "Src/#"path": "Core/Src/#g; s#"-IInc"#"-ICore/Inc"#g'

    # Every source listed in files.cmake must exist (catches a half-moved project)
    if [[ $DRY_RUN -eq 0 ]]; then
        missing=0
        while read -r src; do
            [[ -f "$PROJ/$src" ]] || { printf '      missing: %s\n' "$src" >&2; missing=1; }
        done < <(grep -o '${CMAKE_CURRENT_SOURCE_DIR}/[^"]*' "$PROJ/cmake/files.cmake" | sed 's#${CMAKE_CURRENT_SOURCE_DIR}/##')
        [[ $missing -eq 0 ]] || fail "cmake/files.cmake lists sources that do not exist (see above)."
        info "All sources in cmake/files.cmake exist"
    fi
fi

# ---------------------------------------------------------------------------
title "3. Finding the STM32Cube tools"
# ---------------------------------------------------------------------------
BUNDLES="${CUBE_BUNDLE_PATH:-$HOME/.local/share/stm32cube/bundles}"
[[ -d "$BUNDLES" ]] || fail "No bundle folder at $BUNDLES. Install the STM32Cube extension for VS Code and open any STM32 project once."

# Newest installed version of a bundle (empty if not installed)
latest() { ls -1 "$BUNDLES/$1" 2>/dev/null | grep -E '^[0-9]' | sort -V | tail -1; }

declare -A VER
for b in cmake ninja gnu-tools-for-stm32 st-arm-clangd programmer stlink-gdbserver; do
    VER[$b]="$(latest "$b")"
    [[ -n "${VER[$b]}" ]] || fail "Bundle '$b' is not installed in $BUNDLES."
    info "$(printf '%-20s %s' "$b" "${VER[$b]}")"
done

case "$(uname -s)-$(uname -m)" in
    Linux-x86_64)  PLATFORM="x86_64-linux";  CUBE_OS="linux/x86_64" ;;
    *) fail "Platform $(uname -s)-$(uname -m) is not handled by this prototype." ;;
esac

CUBE_CMAKE="$(ls -d "$HOME"/.vscode/extensions/stmicroelectronics.stm32cube-ide-build-cmake-*/resources/cube-cmake/$CUBE_OS/cube-cmake 2>/dev/null | sort -V | tail -1 || true)"
if [[ -z "$CUBE_CMAKE" && $DO_BUILD -eq 1 ]]; then
    fail "cube-cmake not found. Is the 'STM32Cube build CMake' VS Code extension installed?"
fi

# gdbserver location for launch.json: portable ${userHome} form when the
# bundles live in the default place, literal path otherwise.
GDBSERVER_DIR="$BUNDLES/stlink-gdbserver/${VER[stlink-gdbserver]}/bin"
[[ -x "$GDBSERVER_DIR/ST-LINK_gdbserver" ]] || fail "ST-LINK_gdbserver not found in $GDBSERVER_DIR"
if [[ "$BUNDLES" == "$HOME/.local/share/stm32cube/bundles" ]]; then
    SERVER_CWD="\${userHome}/.local/share/stm32cube/bundles/stlink-gdbserver/${VER[stlink-gdbserver]}/bin"
else
    SERVER_CWD="$GDBSERVER_DIR"
fi

# ---------------------------------------------------------------------------
title "4. Writing configuration files"
# ---------------------------------------------------------------------------
# write_file <relative path>   (content on stdin)
# A file that only holds "{}" is the Empty wizard's placeholder and is
# replaced without --force.
write_file() {
    local rel="$1" dst="$PROJ/$1" content
    content="$(cat)"
    if [[ -e "$dst" ]]; then
        if [[ "$(cat "$dst")" == "$content" ]]; then
            skip "$rel (already up to date)"; return
        fi
        if [[ $FORCE -eq 0 && "$(tr -d ' \t\r\n' < "$dst")" != "{}" ]]; then
            skip "$rel exists and differs — kept (use --force to replace)"; return
        fi
    fi
    if [[ $DRY_RUN -eq 1 ]]; then
        info "$rel (would write)"; return
    fi
    mkdir -p "$(dirname "$dst")"
    [[ -e "$dst" ]] && cp "$dst" "$dst.bak"
    printf '%s\n' "$content" > "$dst"
    info "$rel"
}

lock_entry() {
    cat <<EOF
    {
      "name": "$1",
      "version": "${VER[$1]}",
      "platform": "$PLATFORM",
      "selected_by": [
        {
          "name": "$1",
          "version": "${VER[$1]}"
        }
      ]
    }
EOF
}

# --- .settings: what cube-cmake and the extension use to find the tools
write_file .settings/bundles.store.json <<EOF
{
  "bundles": [
    { "name": "cmake", "version": "${VER[cmake]}" },
    { "name": "ninja", "version": "${VER[ninja]}" },
    { "name": "gnu-tools-for-stm32", "version": "${VER[gnu-tools-for-stm32]}" },
    { "name": "st-arm-clangd", "version": "${VER[st-arm-clangd]}" },
    { "name": "programmer", "version": "${VER[programmer]}" },
    { "name": "stlink-gdbserver", "version": "${VER[stlink-gdbserver]}" }
  ]
}
EOF

write_file .settings/bundles-lock.store.json <<EOF
{
  "resolved": [
$(lock_entry cmake),
$(lock_entry gnu-tools-for-stm32),
$(lock_entry ninja),
$(lock_entry programmer),
$(lock_entry st-arm-clangd),
$(lock_entry stlink-gdbserver)
  ]
}
EOF

# The Empty wizard already writes a correct ide.store.json; keep it.
if [[ "$KIND" == "Empty" && -f "$PROJ/.settings/ide.store.json" ]]; then
    skip ".settings/ide.store.json (kept, written by the wizard)"
else
    write_file .settings/ide.store.json <<EOF
{
  "source": {
    "sourceType": "$([[ "$KIND" == "CubeMX" ]] && echo STM32CubeMX || echo Empty)"
  },
  "board": "$BOARD",
  "device": "$DEVICE",
  "core": "$CORE",
  "order": 0,
  "toolchain": "GCC"
}
EOF
fi

# --- .vscode
GCC_BIN="\${env:CUBE_BUNDLE_PATH}/gnu-tools-for-stm32/${VER[gnu-tools-for-stm32]}/bin"
write_file .vscode/settings.json <<EOF
{
    "cmake.cmakePath": "cube-cmake",
    "cmake.configureArgs": [
        "-DCMAKE_COMMAND=cube-cmake"
    ],
    "cmake.preferredGenerators": [
        "Ninja"
    ],
    "stm32cube-ide-clangd.path": "cube",
    "stm32cube-ide-clangd.arguments": [
        "starm-clangd",
        "--query-driver=$GCC_BIN/arm-none-eabi-gcc*",
        "--query-driver=$GCC_BIN/arm-none-eabi-g++*"
    ],
    // Microsoft's C/C++ IntelliSense competes with clangd for the same files;
    // while it is on, clangd's go-to-definition links between sources never work.
    "C_Cpp.intelliSenseEngine": "disabled"
}
EOF

write_file .vscode/launch.json <<EOF
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "stlinkgdbtarget",
            "request": "launch",
            "name": "STM32Cube: Launch ST-Link GDB Server",
            "origin": "snippet",
            "cwd": "\${workspaceFolder}",
            "preBuild": "\${command:st-stm32-ide-debug-launch.build}",
            "runEntry": "main",
            "imagesAndSymbols": [
                {
                    "imageFileName": "\${command:st-stm32-ide-debug-launch.get-projects-binary-from-context1}"
                }
            ],
            // Launch the real GDB server directly instead of through the "cube"
            // wrapper. VS Code sends SIGTERM to the process it spawned; the cube
            // wrapper does not forward it, so the server survived as an orphan and
            // kept the ST-LINK probe (and port 61234) busy until the board was
            // unplugged. Spawning the server itself makes Stop terminate it cleanly.
            "serverExe": "ST-LINK_gdbserver",
            "serverCwd": "$SERVER_CWD",
            // Safety net: clean up any leftover server after the session ends.
            "postDebugTask": "kill-stlink-gdbserver"
        }
    ]
}
EOF

write_file .vscode/tasks.json <<'EOF'
{
    "version": "2.0.0",
    "tasks": [
        {
            // Safety net for the ST-LINK probe: if a GDB server ever survives the
            // end of a debug session it keeps the probe and port 61234 busy, and
            // the next launch silently fails. This kills any leftover instance.
            // "exit 0" keeps the task green when there is nothing to kill.
            // The [S] keeps pkill from matching (and killing) this task's own
            // shell, whose command line also contains the name.
            "label": "kill-stlink-gdbserver",
            "type": "shell",
            "command": "pkill -f '[S]T-LINK_gdbserver'; exit 0",
            "presentation": {
                "reveal": "silent",
                "panel": "dedicated",
                "close": true
            },
            "problemMatcher": []
        }
    ]
}
EOF

write_file .vscode/c_cpp_properties.json <<'EOF'
{
    "configurations": [
        {
            "name": "STM32",
            "compileCommands": "${workspaceFolder}/build/Debug/compile_commands.json"
        }
    ]
}
EOF

# --- root files
write_file .clangd <<'EOF'
CompileFlags:
  CompilationDatabase: build/Debug
EOF

write_file .gitignore <<'EOF'
build
mx.scratch
*.bak
!.settings
EOF

# ---------------------------------------------------------------------------
title "5. Configure and build (Debug)"
# ---------------------------------------------------------------------------
BUILD_DIR="$PROJ/build/Debug"

# A configure done without the ST tools (e.g. by the system cmake before the
# lock file existed) leaves a cache that never generated build.ninja.
# CMake keeps reusing that broken cache, so it has to go.
if [[ -f "$BUILD_DIR/CMakeCache.txt" && ! -f "$BUILD_DIR/build.ninja" ]]; then
    run "Deleted failed configure in build/Debug" rm -rf "$BUILD_DIR"
fi

if [[ $DO_BUILD -eq 0 || $DRY_RUN -eq 1 ]]; then
    skip "Skipped"
else
    log="$(mktemp)"
    if ! (cd "$PROJ" && "$CUBE_CMAKE" --preset Debug >"$log" 2>&1); then
        tail -20 "$log"; fail "Configure failed (full log: $log)"
    fi
    info "Configure OK"
    if ! (cd "$PROJ" && "$CUBE_CMAKE" --build --preset Debug >"$log" 2>&1); then
        tail -20 "$log"; fail "Build failed (full log: $log)"
    fi
    info "Build OK: build/Debug/$PROJECT_NAME.elf"
    grep -E '^\s*(RAM|FLASH):' "$log" | sed 's/^/      /' || true
    rm -f "$log"
fi

title "Done."
echo "  Open the folder in VS Code (File > Open Folder: $PROJ)."
echo "  If VS Code already had it open, run 'Developer: Reload Window' so the"
echo "  CMake extension picks up the new settings."
echo "  If the CMake extension asks for a preset, choose 'Debug'."
echo "  Debug: Run and Debug > 'STM32Cube: Launch ST-Link GDB Server' (F5)."
