/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

/*
In this workshop we are making a traffic light controller using a STM32F4 microcontroller. 
The traffic light will have three LEDs: red, yellow, and green. 
The program will control the timing of the lights to simulate a real traffic light sequence.
*/

/* STEPS
    AHB1
    GPIOB
        MODER
        OTYPER
        OSPEEDR
        PUPDR
        ODR
    SYSTICK
 */

 uint_t estado_actual = 0;

int main(void)
{
    RCC->AHB1ENR &= ~RCC_AHB1ENR_GPIOBEN; // Enable clock for GPIOB
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN; // Enable clock for GPIOC

    //PB8 - Green LED
    GPIOB->MODER &= ~(GPIO_MODER_MODE8); // Clear mode for pin 8
    GPIOB->MODER |= GPIO_MODER_MODE8_0; // Set pin 8 as output
    GPIOB->OTYPER &= ~(GPIO_OTYPER_OT8); // Set pin 8 as push-pull
    GPIOB->OSPEEDR &= ~(GPIO_OSPEEDR_OSPEED8); // Set pin 8 speed to low
    GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPD8); // Set pin 8 as no pull-up/pull-down
    GPIOB->ODR &= ~(GPIO_ODR_OD8); // PB8 on low

    //PB9 - Yellow LED
    GPIOB->MODER &= ~(GPIO_MODER_MODE9); // Clear mode for pin 9
    GPIOB->MODER |= GPIO_MODER_MODE9_0; // Set pin 9 as output
    GPIOB->OTYPER &= ~(GPIO_OTYPER_OT9); // Set pin 9 as push-pull
    GPIOB->OSPEEDR &= ~(GPIO_OSPEEDR_OSPEED9); // Set pin 9 speed to low
    GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPD9); // Set pin 9 as no pull-up/pull-down
    GPIOB->ODR &= ~(GPIO_ODR_OD9); // PB9 on low

    //PB6 - Red LED
    GPIOB->MODER &= ~(GPIO_MODER_MODE6); // Clear mode for pin 6
    GPIOB->MODER |= GPIO_MODER_MODE6_0; // Set pin 6 as output
    GPIOB->OTYPER &= ~(GPIO_OTYPER_OT6); // Set pin 6 as push-pull
    GPIOB->OSPEEDR &= ~(GPIO_OSPEEDR_OSPEED6); // Set pin 6 speed to low
    GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPD6); // Set pin 6 as no pull-up/pull-down
    GPIOB->ODR &= ~(GPIO_ODR_OD6); // PB6 on low

    //SYSTICK
    SysTick->LOAD = 16000000 - 1; // Set reload register for
	while(1){
        

    };
}
