/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    //0.1
    uint8_t my_variable = 42;

    //0.2
    uint8_t dec = 65;
    uint8_t hex = 0x41;
    uint8_t bin = 0b01000001;
    /*The compiler deals with different representations 
    of the same value but the micro controller gets the same 
    value in memory.*/ 

    //0.3
    uint8_t  a = 255;
    uint16_t b = 255;
    uint32_t c = 255;
    uint8_t  d = 256;
    /*When you assign a value that is too large for a data type,
    it will wrap around to the minimum value of that data type.*/

    uint8_t  e = 257;

    //0.4
    uint8_t a = 200;
    int8_t  b = 200;
    int8_t  c = -1;

    //0.5
    int8_t  x = 127;
    x = x + 1;

    uint8_t y = 255;
    y = y + 1;

    //0.6
    result = 0x0F + 0x01;
    result = 0xFF + 0x01;
    result = 0xA0 + 0x5F;
    result = 0xA0 + 0x60;

    //0.7
    x = 0x01;
    x = 0x02;
    x = 0x04;
    x = 0x08;
    x = 0x10;
    x = 0x20;
    x = 0x40;
    x = 0x80;

    //0.8
    uint8_t a = 5;
    uint8_t b = 0;
    uint8_t c = 255;

    uint8_t r1 = !a;
    uint8_t r2 = !b;
    uint8_t r3 = !c;
    uint8_t r4 = ~c;
    uint8_t r5 = ~a;


	while (1){

    };
}