/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

 // CONFIG

 // RCC.AHB1 pos 0
 // GPIO.MODER 01 pos 5*2
 // GPIO.OUTPUTTYPE 0 pos 5
 // GPIO.SPEED 00 pos 5*2
 // GPIO.PUPDR 01 pos 5*2
 // GPIO.ODR 1 pos 5

#include <stm32f4xx.h>
#include <stdint.h>

//global variable to hold the state of the push button
volatile uint32_t push_button_state = 0; 

int main(void)
{
    // GPIOA pin 5 is connected to the on-board LED
    /* step 1:RCC.AHB1 */
    RCC->AHB1ENR |= (1 << 0); // Enable GPIOA clock
    /* step 2:GPIO.MODER */
    GPIOA->MODER &= ~(0b11 << (5 * 2)); // Clear
    GPIOA->MODER |= (0b01 << (5 * 2)); // Set as output
    /* step 3:GPIO.OTYPER */
    GPIOA->OTYPER &= ~(1 << 5); // Clear and  set push-pull (0)
    /* step 4:GPIO.OSPEEDR */
    GPIOA->OSPEEDR &= ~(0b11 << (5 * 2));
    /* step 5:GPIO.PUPDR */
    GPIOA->PUPDR &= ~(0b11 << (5 * 2));
    /* step 6:GPIO.ODR */
    // Power on the LED A5
    GPIOA->ODR &= ~(1 << 5); // Clear
    GPIOA->ODR |= (1 << 5); // LED on
    /* Loop forever */
	while(1)
    {
        // Toggle the LED
    };
}
